blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('tableau/', views.TableauListView, name='tableau'),
    path('peintre/',views.PeintreListView.as_view(), name="peintre"),
    path('tableau/<int:pk>', views.TableauDetailView, name='tableau-detail'),
    path('addcomments/<int:pk>', views.addComments, name='add-comments'),
    path('mon-compte/', views.MonCompte, name='compte'),
    path('connexion/', views.Connexion, name='connexion'),
    path('administration/', views.AdministrationSite, name='administration'),
    path('modifier-tableau/<int:pk>', views.UpdateTableau, name='modifier-tableau'),
    path('ajouter-tableau/', views.CreateTableau, name='ajouter-tableau'),
    path('search-tableau/', views.SearchTableau, name='search'),
    path('addtype/',views.AddType,name='addtype'),
    path('filtre/',views.FiltreTableau, name='filtre'),
    path('contact/', views.Contact, name='contact'),

]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

siteWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls')),
    path('',RedirectView.as_view(url='blog/',permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from pyexpat import model
from statistics import mode
from django.db import models
from django.urls import reverse

# Create your models here.


class Tableau(models.Model):
    """ Model représentabnt les tableaux"""
    nom_tableau = models.CharField(max_length=200)
    description = models.CharField(max_length=250)
    longueur = models.CharField(max_length=50)
    largeur = models.CharField(max_length=50)
    date_debut = models.DateField()
    date_fin = models.DateField()
    type = models.ForeignKey('Type', on_delete=models.SET_NULL, null=True)
    photo = models.ImageField(upload_to='images/')
    peintre = models.ForeignKey('Peintre', on_delete=models.SET_NULL, null=True)
    meilleur_realisation = models.CharField(max_length=10)
    affichage = models.BooleanField()

    def __str__(self):
        return self.nom_tableau

    def get_absolute_url(self):
        return reverse("tableau-detail", args=[str(self.id)])

class Type(models.Model):
    """ Model représentant les types de peinture """
    type_nom = models.CharField(max_length=100)

    def __str__(self):
        return self.type_nom
    



class Peintre(models.Model):
    """ Model représentant les peintres"""
    nom = models.CharField(max_length=100)
    prenom = models.CharField(max_length=100)
    date_naissance = models.DateField(null=True, blank=True)
    description_peintre = models.CharField(max_length=250)
    
    class Meta:
        ordering = ['nom', 'prenom']

    def get_absolute_url(self):
        return reverse("peintre-detail", args=[str(self.id)])
    
    def __str__(self):
        return f'{self.nom} {self.prenom}'

class Commentaire(models.Model):
    """ Model représentant les commentaires sur les tableaux """

    personne = models.CharField(max_length=50)
    texte = models.TextField(null=True)
    date_publication = models.DateField(null=True)
    tableau = models.ForeignKey('Tableau', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f'{self.personne} {self.tableau}'
    

blog/forms.py
from django import forms
from blog.models import Tableau


class AddComments(forms.Form):
    personne = forms.CharField(max_length=50, required=True)
    texte = forms.CharField(widget=forms.Textarea, required=True)

class FormTableau(forms.ModelForm):
    class Meta:
        model = Tableau
        fields = ['nom_tableau', 'description','longueur','largeur','date_debut','date_fin','type','photo','peintre','affichage']


class FormAddType(forms.Form):
    type_nom = forms.CharField(max_length=100, required=True)

class formContact(forms.Form):
    Nom = forms.CharField(max_length=50, required=True, widget=forms.TextInput(attrs={'placeholder': 'Votre nom'}))
    Prenom = forms.CharField(max_length=50, required=True, widget=forms.TextInput(attrs={'placeholder': 'Votre prénom'}))
    Email = forms.EmailField(max_length=150, required=True, widget=forms.TextInput(attrs={'placeholder': 'Votre Email'}))
    Message = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Votre message'}), max_length=2000, required=True)

blog/views.py
import datetime
from glob import escape
from shutil import register_unpack_format
from urllib.request import Request
from urllib.robotparser import RequestRate
from django.http import Http404, HttpResponse
from django.shortcuts import redirect, render
from django.views import generic
from .models import Peintre, Tableau, Commentaire, Type
from blog.forms import AddComments, FormAddType, FormTableau, formContact
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from django.core.mail import send_mail, BadHeaderError

# Create your views here.


def index(request):
    num_tableau = Tableau.objects.all()
    tableau = Tableau.objects.filter(affichage=True).order_by('id')[:3]
    nombre_tableau = 0
    for affiche in num_tableau:
        if affiche.affichage == True:
            nombre_tableau += 1
    


    context = {
        'num_tableau' : nombre_tableau,
        'tableau' : tableau,
        'page' : 'home'
    }

    return render(request, 'index.html', context=context)

def Contact(request):

    if request.method == 'POST':
        form = formContact(request.POST)
        if form.is_valid():
            subject = 'Contact Site' 
            body = {
			'first_name': form.cleaned_data['Nom'], 
			'last_name': form.cleaned_data['Prenom'], 
			'email': form.cleaned_data['Email'], 
			'message':form.cleaned_data['Message'], 
			}
            message = "\n".join(body.values())
            try:
                send_mail(subject, message, 'matteo@matteo-bonneval.fr', ['matteobonneval19@gmail.com']) 
            except BadHeaderError:
                return render(request, 'blog/contact.html', context={'page':'contact','form' : form,'succes':True})
            return render(request, 'blog/contact.html', context={'page':'contact','form' : form,'succes':True})
    
    form = formContact()
    return render(request, 'blog/contact.html', 
    context={
        'page':'contact',
        'form' : form,
        'succes':None
        })




def TableauListView(request):

    vue = request.GET.get('filtre')
    print(vue)
    if vue == 'tous' or vue == None:
        tableau = Tableau.objects.all()
    else:
        if vue == 'Alain' or vue == 'Nadine':
            peintre = Peintre.objects.get(prenom = vue)
            print(peintre)
            tableau = Tableau.objects.filter(peintre = peintre)
        else:
            type = Type.objects.get(type_nom = vue)
            tableau = Tableau.objects.filter(type = type)
        
    


    context={
        'tableau':tableau,
        'vue' :vue,
        'page' : 'tableau'
    }

    return render(request, 'blog/tableau_list.html' , context=context)


class PeintreListView(generic.ListView):
    model = Peintre


def TableauDetailView(request, pk):
    try:
        tableau = Tableau.objects.get(id=pk)
        form = AddComments()
    except Tableau.DoesNotExist:
        raise Http404("Le tableau n'existe pas")
    return render(request,'blog/tableau_detail.html',{
        'tableau':tableau, 
        'form':form,
        'page' : 'tableau'
    })

def addComments(request, pk):
    personne = escape(request.POST.get('personne'))
    texte = escape(request.POST.get('texte'))
    date = datetime.datetime.now().date()
    tableau = Tableau.objects.get(id=pk)

    commentaire = Commentaire(personne=personne, texte=texte, date_publication=date, tableau=tableau)

    commentaire.save()


    return render(request, 'comments/comments.html', context={'commentaire' : commentaire})

@login_required
def MonCompte(request):
    return render(request, 'registration/compte.html')


def Connexion(request):
    return render(request, 'registration/connexion.html')

@login_required
def AdministrationSite(request):
    tableau = Tableau.objects.all()

    return render(request,'registration/administration.html', {'tableau':tableau})


@csrf_exempt
@login_required
def CreateTableau(request):
    form = FormTableau()
    form_type = FormAddType()
    if request.method == 'POST':
        form = FormTableau(request.POST, request.FILES)
        if form.is_valid():
            tableau = form.save(commit=False)
            peintre = Peintre.objects.get(pk=request.POST.get('peintre'))
            tableau.peintre = peintre
            tableau.save()
            redirect('administration')

    peintre = Peintre.objects.all()
    context = {
        'peintre':peintre,
        'form':form,
        'form_type':form_type
    }
    return render(request, 'registration/ajout_tableau.html', context=context)


@csrf_exempt
@login_required
def UpdateTableau(request, pk):
    try:
        tableau = Tableau.objects.get(id=pk)
        
        if request.method == 'POST':
            form = FormTableau(request.POST,request.FILES, instance=tableau)
            if form.is_valid():
                print(request.FILES)
                tableau = form.save(commit=False)
                peintre = Peintre.objects.get(pk=request.POST.get('peintre'))
                tableau.peintre = peintre
                tableau.save()
                return redirect('administration')
        else:
            form = FormTableau(instance=tableau)

        context = {
                'form':form,
            }

    except Tableau.DoesNotExist:
        raise Http404("Le tableau n'existe pas")
    return render(request,'registration/modifier_tableau.html',context=context)



def SearchTableau(request):
    name_tableau = escape(request.POST.get('recherche'))
    tableau = Tableau.objects.filter(nom_tableau__icontains = name_tableau)
    return render(request, 'comments/searchTableau.html', context={'tableau':tableau})

def FiltreTableau(request):
    peintre = escape(request.POST.get('peintre'))
    type = escape(request.POST.get('type'))
    date = escape(request.POST.get('date'))

    if peintre == "" and type == "":
        if date == 'date-r':
            tableau = Tableau.objects.filter()
        else:
            tableau = Tableau.objects.filter()
    elif peintre == "" and type != "":
        tableau = Tableau.objects.filter(type = type)
    elif peintre != "" and type == "":
        tableau = Tableau.objects.filter(peintre = peintre)
    else:
        tableau = Tableau.objects.filter(peintre = peintre, type = type)
        
    return render(request, 'comments/searchTableau.html', context={'tableau':tableau})



    



@csrf_exempt
@login_required
def AddType(request):
    type_nom = escape(request.POST.get('type_nom'))
    type = Type(type_nom=type_nom)
    type.save()
    return redirect('ajouter-tableau')


def page_not_found_view(request):
    return render(request,'404.html', context={})

blog/templates/blog/contact.html
{% extends "base_generic.html" %}

{% block content %}
    <div class="contain-title-contact">
        <h3>Nous contacter</h3>
    </div>
    {% if succes == True %}
        <p style="text-align:center">Le mail a bien été envoyé</p>
    {% elif succes == False %}
        <p style="text-align:center">Le mail n'a pas pu être envoyé</p>
    {% endif %}
    <div class="contain-form-contact">
        <form action="{% url 'contact' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Envoyer</button>
        </form>
    </div>
{% endblock %}

blog/templates/blog/peintre_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Liste des peintres</h1>
  {% if peintre_list %}
  <ul>
    {% for peintre in peintre_list %}
      <li>
        <p>
          {{ peintre.nom }} {{ peintre.prenom }}
        </p>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Il n'y a aucun peintre</p>
  {% endif %}
{% endblock %}

blog/templates/blog/tableau_detail.html
{% extends "base_generic.html" %}



{% block content %}
<section class="contain-detail">
{% if tableau.affichage == False %}
    <p class="center"> Ce lien ne renvoie sur aucun tableau</p>
    <a href="{% url 'tableau' %}">Retour aux Tableaux</a>
{% else %}
  <a class="retour barre-a" href="{% url 'tableau' %}">Retour à la liste</a>
  <div class="corps-detail">
    
    <div class="detail-image">
      <img src="{{ tableau.photo.url }}" alt="">
    </div>
    <div class="detail-texte">
      <h1>{{ tableau.nom_tableau }}</h1>
      <p>{{ tableau.description}}</p>
      <p>by <a href="{% url 'peintre' %}">{{ tableau.peintre }}</a></p>
      <p>Dimension : {{ tableau.longueur }} x {{ tableau.largeur }} cm</p>
      <p>Date : {{ tableau.date_debut }} - {{ tableau.date_fin }}</p>
      <p>Type : {{ tableau.type }}</p>
    </div>
   
  </div>
 
<div id="comments" class="contain-commentaire">
  <h3>Vos commentaires</h3>
  {% if tableau.commentaire_set.all %}
    {% for commentaire in tableau.commentaire_set.all %}
      <div class="commentaire">
        <h5><div class="commentaire-rond"><i class="fa-solid fa-user"></i></div>{{ commentaire.personne }}</h5>
        <p class="date">Commenté le {{ commentaire.date_publication }}</p>
        <p>{{ commentaire.texte }}</p>
      </div>
    {% endfor %}
  {% else %}
    <p class="center">Aucun commentaire</p>
  {% endif %}
</div>
{% block formulaire %}
  <form>
    <h3>Ajouter votre commentaire</h3>
    {% csrf_token %}
    {{ form }}
    <button hx-post="{% url 'add-comments' tableau.id %}"
            hx-target="#comments"
            hx-swap="beforeend"
    type="submit">Publier</button>
  </form>
{% endblock %}
{% endif %}
</section>
{% endblock %}

blog/templates/blog/tableau_list.html
{% extends "base_generic.html" %}

{% block content %}
<section class="contain-tableau">
  <div class="headen">
    <a {% if vue == "Tous" or vue == None %}class="active" {% endif %} href="{% url 'tableau' %}?filtre=tous">Tous</a>
    <a {% if vue == "Nadine" %}class="active" {% endif %} href="{% url 'tableau' %}?filtre=Nadine">Nadine</a>
    <a {% if vue == "Alain" %}class="active" {% endif %} href="{% url 'tableau' %}?filtre=Alain">Alain</a>
    <a {% if vue == "Pastel" %}class="active" {% endif %} href="{% url 'tableau' %}?filtre=Pastel">Pastel</a>
    <a {% if vue == "Aquarelle" %}class="active" {% endif %} href="{% url 'tableau' %}?filtre=Aquarelle">Aquarelle</a>
    <a {% if vue == "Acrylique" %}class="active" {% endif %} href="{% url 'tableau' %}?filtre=Acrylique">Acrylique</a>
    <a {% if vue == "Huile" %}class="active" {% endif %} href="{% url 'tableau' %}?filtre=Huile">Huile</a>
    <a {% if vue == "Mixte" %}class="active" {% endif %} href="{% url 'tableau' %}?filtre=Mixte">Technique Mixte</a>

  </div>
  <div class="corps" id="search">
    {% if tableau %}
        {% for tableau in tableau %}
          {% if tableau.affichage != False %}
          <a href="{% url 'tableau-detail' tableau.id %}">
            <div class="tableau">
              <div class="image-tableau">
                <img src="{{ tableau.photo.url }}" alt="">
              </div>
              <div class="text-tableau">
                <h3>
                  {{ tableau.nom_tableau }}
                </h3>
                <p>
                  {{ tableau.peintre }}
                </p>
                <button>Voir tableau</button>
              </div>
              
            </div>
          </a>
          {% endif %}
        {% endfor %}
    {% else %}
      <p>Il n'y a aucun tableau</p>
    {% endif %}
  </div>
</section>
{% endblock %}